name: Deploy API QR Code Gen

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/qrcode-api:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/qrcode-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image Docker
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/qrcode-api:latest

      - name: Run Docker Container
        run: |
          docker stop qrcode-api || true
          docker rm qrcode-api || true
          docker run -d -p 80:8080 --name qrcode-api \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION=us-east-2 \
            -e AWS_BUCKET_NAME=qrcode-store-gen \
            ${{ secrets.DOCKER_USERNAME }}/qrcode-api:latest
